[package]
name = "advent-of-code-2021"
version = "0.1.0"
authors = ["Bryce Kalow"]
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
